version: '3.0'
services:

  server: 
    container_name: server
    env_file: 
      - ./server/.development.env
    build: 
      context: ./server/
      dockerfile: ./server.dockerfile
    ports: 
      - 5000:5000
    command: npm run start
    depends_on:
      - postgres
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    links:
    - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: 
      - ./server/.development.env
    environment: 
      PG_DATA: /var/lib/postgresql/data
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  migrations:
    build: 
      context: ./server/
      dockerfile: ./migrations.dockerfile
    depends_on: 
      - postgres
    links: 
      - postgres

volumes: 
  pgdata: 